- name: Stop Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Deallocate the virtual machine
    azure_rm_virtualmachine:
      resource_group: ansible
      name: ansibleVM
      allocated: no
