- name: Create Azure VM
  hosts: all
  connection: local
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: ansible
      location: eastasia
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: ansible
      name: ansibleVnet
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: ansible
      name: ansibleSubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: ansibleVnet
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: ansible
      allocation_method: Static
      name: ansiblePublicIP
    register: output_ip_address
  - name: Dump public IP for VM which will be created
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
  - name: Artifact Public IP to Tower Workflows
    set_stats:
      data:
        newVMIP: "{{ output_ip_address.state.ip_address }}"
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: ansible
      name: ansibleNetworkSecurityGroup
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network inteface card
    azure_rm_networkinterface:
      resource_group: ansible
      name: ansibleNIC
      virtual_network: ansibleVnet
      subnet: ansibleSubnet
      public_ip_name: ansiblePublicIP
      security_group: ansibleNetworkSecurityGroup
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: ansible
      name: "{{ vmname }}"
      vm_size: Standard_DS1_v2
      admin_username: garylau
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/garylau/.ssh/authorized_keys
          key_data: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCQl0O2sj5bEoMeKjZFrKkoT9eEwHwAYGi5TFjSb5KgucHEWKB1l8q0J19kcPM69B+Bx4X9mZ+TdqWPxcdfrI23jmeAAKP/GiPUArzlIrrya+3AiX8So7xZhFjZJ0qJ4QDW36JVW18NsHEnEPKCcK4/6ODfGAY3fTgiAGcu2f0p46a/KEf2WIF0BArXPRV1LI24NIAGpR+sEo+lg6kaLaSbD8TWPJnfBwaPJHGHKqVBwPeNIs7J6IaoW1rPR8piejmlppkwSdslcZTuASrg5XQTz2dx4PcCTYD20nGSfF1itPnlkA136Bif6dHPOz5D4FRu+ekTkQrlxII2lAU0lhHp garylau@ansible-tower.lab.loc
      network_interfaces: ansibleNIC
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest
